### ISSUE TITLE
Naming of models

### ISSUE THREAD

**Issue by karalets** [choderalab/pinot#2]
At the danger of being a Bayesian fascist here, let me make some recommendations for naming conventions.

I.e. the file ```gaussian_variational.py``` is just defining a maximum likelihood graph_nn, the word variational is not just misleading here but there is nothing variational happening at all, as this is an inference property.

Suggestion:
Name models for model properties, i.e. ```model_graph_nn_gaussian.py``` or so.
And we can name inference things accordingly.

**Comment by yuanqing-wang** [comment]
fixed.

but we might get rid of this script to further separate things eventually
