### ISSUE TITLE
memory leak in `pinot.TrainAndTest`?

### ISSUE THREAD

**Issue by yuanqing-wang** [choderalab/pinot#23]
seems that this is taking unexpectedly large memory. 
https://github.com/choderalab/pinot/blob/9532b235ae1613ab71d7bcddde79dfacca357abf/pinot/app/experiment.py#L134

**Comment by maxentile** [comment]
How much memory usage is expected, and how much is happening?

Note that Train stores all iterates in memory, in the `states` dictionary, so I'd expect this to use `n_epochs` x `size(model)` memory.

**Comment by yuanqing-wang** [comment]
Yes, the state dictionaries are all saved. 

One state dictionary takes around 500K. Even stored each iteration, 2000 iterations will only give us around 100M.

**Comment by dnguyen1196** [comment]
Added context: https://github.com/choderalab/pinot/blob/infrastructure/scripts/heteroscedastic_vs_homoscedastic/run.py

reproduces this. @yuanqing-wang can confirm

**Comment by dnguyen1196** [comment]
My suspicion is that when you call `result = train_and_test.run()`, you not only copy the value of "result" which is a list of MSE/error numbers but also the entire computation graph. Because when pytorch uses a variable, that variable is a node, part of a huge computation graph. So perhaps, you need to explicitly extract the value of the variable result

`    def run(self):
        results = []

        for param_dict in self.param_dicts:
            train_and_test = self.experiment_generating_fn(param_dict)
            result = train_and_test.run()
            results.append((param_dict, result))
            del train_and_test

        self.results = results

        return self.results`

**Comment by yuanqing-wang** [comment]
Thanks! tried but still have the same issue

**Comment by yuanqing-wang** [comment]
@dnguyen1196 

You're right! Sorry I misunderstood your point. The metrics weren't `detach()`ed in the previous implementation. So I was copying giant computation graphs thousands of times. Fixed here 9532b23

**Comment by maxentile** [comment]
>Because when pytorch uses a variable, that variable is a node, part of a huge computation graph and this takes up a lot of memory. So perhaps, you need to explicitly extract the value of the variable result

Good sleuthing!

>Fixed here a6a41d4

Do you ever need to take derivatives of things in `metrics.py`? Or are these used only for evaluation and report-generation? (The comment at the top of `metrics.py` says these might also be used for training.)

**Comment by yuanqing-wang** [comment]
moved the detach step in the report generation step
